<?xml version="1.0"?>
<algebra>
  <basicAlgebra>
    <algName>six6</algName>
    <desc>intransitive G set. |G| = 3.</desc>
    <cardinality>6</cardinality>
    <operations>
      <op>
        <opSymbol>
          <opName>f</opName>
          <arity>1</arity>
        </opSymbol>
        <opTable>
          <intArray>
            <row>1,2,0,4,5,3</row>
          </intArray>
        </opTable>
      </op>
    </operations>
  </basicAlgebra>
</algebra>
