<?xml version="1.0"?>
<algebra>
  <basicAlgebra>
    <algName>cib3_two_min_abs</algName>
    <cardinality>3</cardinality>
    <operations>
      <op>
        <opSymbol>
          <opName>o</opName>
          <arity>2</arity>
        </opSymbol>
        <opTable>
          <intArray>
            <row r="[0]">0,1,2</row>
            <row r="[1]">1,1,0</row>
            <row r="[2]">2,0,2</row>
          </intArray>
        </opTable>
      </op>
    </operations>
  </basicAlgebra>
</algebra>
